name: Puppeteer Runner

on:
  push:
    branches: [main]

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer
        run: node index.js || echo "scraping error"
        continue-on-error: true

      - name: Backup result dan push ke screenshots branch
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          cp -r result /tmp/screenshots-result
      
          git checkout --orphan screenshots
          git rm -rf .
          git clean -fdx

          cp -r /tmp/screenshots-result/* ./
      
          git add .
          git commit -m "Update screenshot"
          git push --force origin screenshots
